SELECT b.CATEGORY, SUM(s.SALES)
FROM BOOK b LEFT OUTER JOIN BOOK_SALES s
ON b.BOOK_ID=s.BOOK_ID
WHERE s.SALES_DATE LIKE '2022-01-%'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY

# -- 코드를 입력하세요
# SELECT b.CATEGORY as CATEGORY, SUM(s.SALES) as TOTAL_SALES
# FROM BOOK b INNER JOIN BOOK_SALES s
# ON b.BOOK_ID = s.BOOK_ID
# WHERE s.SALES_DATE LIKE '2022-01-%'
# GROUP BY b.CATEGORY
# ORDER BY b.CATEGORY